### ISSUE TITLE
Listener returns are not used

### ISSUE THREAD

**Issue by microsoftly** [bogus34/bookshelf-schema#5] opened 2016-08-30 17:24 UTC
When I return a promise from a Listener defined using bookshelf schema, execution does not wait until the promise resolves. When I move the same block of code to a listener as defined with bookshelf I get the expected behavior

**Comment by bogus34** [comment] 2016-08-30 22:29
Confirmed. Thanks @matts310, should be fixed soon.

**Comment by bogus34** [comment] 2016-09-05 19:10
seems to be fixed now

**Closed as completed by bogus34** 2016-09-05 19:10 UTC
Labels: bug
